# Generated by Django 4.1.2 on 2022-10-14 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('passwords', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='passwordmodel',
            name='name',
            field=models.CharField(max_length=256, unique=True),
        ),
        migrations.AlterField(
            model_name='passwordmodel',
            name='password',
            field=models.BinaryField(max_length=256),
        ),
    ]
